import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ROUTINE-AND-MONEY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}